### ISSUE TITLE
Use RequestContextManager

### ISSUE THREAD

**Issue by iurisilvio** [opentracing-contrib/python-flask#20]
Related to https://github.com/uber-common/opentracing-python-instrumentation/issues/52

I'm trying to use `install_all_patches()` but the instrumentation spans are not attached to the current request, because this module doesn't use `RequestContextManager`. I think this behaviour should be the default or at least easy to setup.

**Comment by yurishkuro** [comment]
@iurisilvio RequestContextManager is a non-standard mechanism that exists only in the library you mentioned. I have a branch, based on @carlosalberto 's work, that implements support for OT 2.0 and scope managers (https://github.com/yurishkuro/opentracing-python-instrumentation/tree/ot_scopemanager_integration)

With that branch, this project still doesn't work correctly because of #18 (but I tried to hack it to use start_active_span and it works, so hopefully it will get merged here soon).

**Comment by iurisilvio** [comment]
I understand. OpenTracing libs are still evolving, I'm looking forward to use them.

Thanks for your work!

**Comment by trondhindenes** [comment]
Same here, its (too) hard to wire up a flask app together with `opentracing-python-instrumentation`. As far as I understand, solving this issue will align the two libraries so that the fit together?

**Comment by wjoel** [comment]
@yurishkuro Now that https://github.com/opentracing-contrib/python-flask/issues/18 has been merged, is it possible to get your branch merged into `opentracing-python-instrumentation` and new releases of both projects with support for OT 2.0?

**Comment by wjoel** [comment]
Any update on this, @yurishkuro or @carlosalberto?

**Comment by carlosalberto** [comment]
@wjoel @yurishkuro I've released the `1.0.0` version which supports OT 2.0 ;) 

Let me know.

**Comment by ptmcg** [comment]
This package is no longer being maintained, users should migrate to the `opentelemetry-api` package.

Closing.
