### ISSUE TITLE
Question: Release Status

### ISSUE THREAD

**Issue by zrayn** [opentracing-contrib/python-flask#38]
What is the status of getting master released? I need the broader opentracing version pinning in order to incorporate this library into my project, and master seems to work in my project, but I would much prefer to install a released package.

**Comment by Jamim** [comment]
Hi @carlosalberto,
Can you please issue a new release?
Also, #41 might be useful for that.

**Comment by Jamim** [comment]
cc @yurishkuro

**Comment by lukacsg** [comment]
+1
Can you take in #39 too?

**Comment by madmaze** [comment]
cc @kcamenzind

**Comment by Jamim** [comment]
Hello @carlosalberto,

First of all, thank you for your recent work on this library!

Unfortunately, deploying of `1.1.0` [has failed](https://travis-ci.org/opentracing-contrib/python-flask/jobs/600396363).
I've prepared a corresponding fix: #43.
Could you please merge it and force push the `1.1.0` tag in order to trigger publishing of a fixed package?

Thanks again!

**Comment by Jamim** [comment]
Hi everyone,
[Flask-OpenTracing 1.1.0](https://pypi.org/project/Flask-OpenTracing/1.1.0/) is available on PyPI now :tada:
Thank you @carlosalberto for releasing it!

**Comment by lukacsg** [comment]
@Jamim  @carlosalberto 
Could you make a release with #39 too? We are waiting this to use it in production. This changes would be used in the Seldon-core package as well. (connected to this issue: https://github.com/SeldonIO/seldon-core/issues/719)

Thanks

**Comment by zrayn** [comment]
Closing this issue since the original goal has been accomplished. I'll let someone else open a separate issue for #39 if they would like to.
