### ISSUE TITLE
Still remainders of mock

### ISSUE THREAD

**Issue by mcepl** [opentracing-contrib/python-flask#58]
To complete the clean-up of the separate mock module you forgot few lines:

```diff
---
 setup.py                    |    1 -
 tests/test_flask_api.py     |    2 +-
 tests/test_flask_tracing.py |    2 +-
 3 files changed, 2 insertions(+), 3 deletions(-)

--- a/setup.py
+++ b/setup.py
@@ -30,7 +30,6 @@ setup(
         'tests': [
             'flake8',
             'flake8-quotes',
-            'mock',
             'pytest',
             'pytest-cov',
         ],
--- a/tests/test_flask_api.py
+++ b/tests/test_flask_api.py
@@ -1,6 +1,6 @@
-import mock
 import pytest
 import unittest
+from unittest import mock
 
 import opentracing
 from flask import Flask
--- a/tests/test_flask_tracing.py
+++ b/tests/test_flask_tracing.py
@@ -1,5 +1,5 @@
-import mock
 import unittest
+from unittest import mock
 
 from flask import (Flask, request)
 import opentracing
```

**Comment by ptmcg** [comment]
Fortunately `mock` keeps forward/backward compatibility, so leaving these in as-is should be benign.

Would be a good hygiene issue worth working if this were an active package, but this package has had no updates since 2019, and the most recent 2.0.0 release was just to keep things working with recent Flask 3 release. Users should migrate to the opentelemetry-api, which includes a shim to simplify migration from this package.

Closing.
